inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - 'Rakefile'
    - 'feast.gemspec'
  NewCops: enable
  EnabledByDefault: true
  TargetRubyVersion: 3.1

